---
# tasks file for openrazer - Ubuntu OS

- name: Ubuntu OS | Adding repository {{ openrazer_repo }}
  ansible.builtin.apt_repository:
    repo: "{{ openrazer_repo }}"
    state: "{{ openrazer_repo_desired_state }}"
    filename: "{{ openrazer_repo_filename }}"
    codename: "{{ ansible_lsb['codename'] }}"
    update_cache: yes

- name: Ubuntu OS | Installing {{ openrazer_app }}
  ansible.builtin.apt:
    name: "{{ openrazer_app }}"
    state: "{{ openrazer_package_desired_state }}"
    force_apt_get: yes
    update_cache: yes
