---
# tasks file for openrazer - Ubuntu

- name: Adding repository {{ openrazer_repo }} on Ubuntu systems
  apt_repository:
    repo: "{{ openrazer_repo }}"
    state: "{{ openrazer_repo_desired_state }}"
    filename: "{{ openrazer_repo_filename }}"
    update_cache: yes
- name: Installing {{ openrazer_app }} on Ubuntu systems
  apt:
    name: "{{ openrazer_app }}"
    state: "{{ openrazer_package_desired_state }}"
    force_apt_get: yes
    update_cache: yes
